// <auto-generated />
namespace MilenaSapunova.TerminateContracts.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Addaddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addaddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201710150153150_Add address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
