// <auto-generated />
namespace MilenaSapunova.TerminateContracts.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Addcompany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addcompany));
        
        string IMigrationMetadata.Id
        {
            get { return "201710150118185_Add company"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
