// <auto-generated />
namespace MilenaSapunova.TerminateContracts.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Fixuserproperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fixuserproperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201710161301546_Fix user properties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
